{{- if and .Values.tls.useCertManager .Values.tls.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "ndots-webhook.issuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ndots-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
