{{- if .Values.tls.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "k8s-ndots-admission-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-ndots-admission-controller.labels" . | nindent 4 }}
spec:
  secretName: {{ include "k8s-ndots-admission-controller.tlsSecretName" . }}
  duration: {{ .Values.tls.certManager.duration }}
  renewBefore: {{ .Values.tls.certManager.renewBefore }}
  subject:
    organizations:
      - k8s-ndots-admission-controller
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - digital signature
    - key encipherment
  dnsNames:
    - {{ include "k8s-ndots-admission-controller.fullname" . }}
    - {{ include "k8s-ndots-admission-controller.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "k8s-ndots-admission-controller.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "k8s-ndots-admission-controller.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "k8s-ndots-admission-controller.issuerName" . }}
    kind: {{ .Values.tls.certManager.issuer.kind }}
{{- end }}
