{{- if and .Values.tls.useCertManager .Values.tls.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "k8s-ndots-admission-controller.issuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-ndots-admission-controller.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
