apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ndots-admission-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-ndots-admission-controller.labels" . | nindent 4 }}
  {{- $promAnnotations := and .Values.metrics.enabled (not .Values.metrics.serviceMonitor.enabled) }}
  {{- if or .Values.commonAnnotations $promAnnotations }}
  annotations:
    {{- if $promAnnotations }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port | quote }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "k8s-ndots-admission-controller.selectorLabels" . | nindent 4 }}
